baseURL: https://www.ig2.org
languageCode: ja-jp
defaultContentLanguage: ja
title: obメモ
theme: cupper-hugo-theme
googleAnalytics: UA-173566269-1
# disqusShortname: yourdiscussshortname
enableGitInfo: true

publishDir: docs

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  # description: An accessibility-friendly Hugo theme, ported from the [original Cupper](https://github.com/ThePacielloGroup/cupper) project.
  description: obcat のメモおきば
  # homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  homeMetaContent: obcat のメモおきば
  footer: "&copy; 2020 obcat"
  # For more date formats see https://gohugo.io/functions/format/
  # dateFormat: Jan 2, 2006
  dateFormat: 2006-01-02
  # codePenUser: someUser
  katex: true
  darkThemeAsDefault: false
  hideHeaderLinks: false
  search: true
  # A list of custom css files can be provided, which must be placed inside
  # 'static/'.
  # This is useful to override just specific css classes, instead of copying
  # the entire theme's css file to your own site.
  # Usage:
  # customCss:
  #   - css/foo.css # relative path starting from static/
  #- css/bar.css
  customCss:
    - css/add_on.css

menu:
  nav:
    - name: ホーム
      url: /
      weight: 1
    - name: メモ一覧
      url: /post/
      weight: 2
    - name: タグ一覧
      url: /tags/
      weight: 3
    # - name: About
    #   url: /about/
    #   weight: 4
    # - name: RSS
    #   url: /index.xml
    #   weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
